export const ERROR_CODES = {
  // 認證錯誤 (AUTH_)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_003',

  // 問卷錯誤 (SURVEY_)
  SURVEY_CONSENT_REQUIRED: 'SURVEY_001',
  SURVEY_INVALID_NPS: 'SURVEY_002',
  SURVEY_DUPLICATE_SUBMIT: 'SURVEY_003',

  // 資料庫錯誤 (DB_)
  DB_NOT_FOUND: 'DB_001',
  DB_CONNECTION_FAILED: 'DB_002',
  DB_UNIQUE_CONSTRAINT: 'DB_003',

  // 驗證錯誤 (VALIDATE_)
  VALIDATE_MISSING_FIELD: 'VALIDATE_001',
  VALIDATE_INVALID_FORMAT: 'VALIDATE_002',
} as const
